name: ci
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      MUJOCO_GL: egl      # headless; no rendering in CI
      ENV_BACKEND: "NullEnv"
      PYTHONDONTWRITEBYTECODE: 1
      PIP_NO_INPUT: 1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate System Slice (schema + physics_hash)
        run: |
          python tools/validate_system_slice.py configs/system_slice.yaml schemas/system_slice.schema.json --strict

      - name: Run tests
        run: |
          pytest -q --disable-warnings --maxfail=1
